---
services:
  loader-runner:
    build:
      context: .
    environment:
      DEPLOY_START_TIME: "${DEPLOY_START_TIME}"
      FACTSET_SERIAL: "${FACTSET_SERIAL}"
      FACTSET_USER: "${FACTSET_USER}"
      FDS_LOADER_PATH: "${FDS_LOADER_PATH}"
      FDS_LOADER_SOURCE_PATH: "${FDS_LOADER_SOURCE_PATH}"
      FDS_LOADER_ZIP_FILENAME: "${FDS_LOADER_ZIP_FILENAME}"
      LOG_LEVEL: "${LOG_LEVEL}"
      MACHINE_CORES: "${MACHINE_CORES}"
      PGDATABASE: "${PGDATABASE}"
      PGHOST: "${PGHOST}"
      PGPASSWORD: "${PGPASSWORD}"
      PGPASSWORD_ENCRYPTED: "${PGPASSWORD_ENCRYPTED}"
      PGUSER: "${PGUSER}"
      WORKINGSPACEPATH: "${WORKINGSPACEPATH}"
    volumes:
      - type: bind
        source: mounts/workingspace
        target: "${WORKINGSPACEPATH}"
      - type: bind
        source: mounts/factset-loader
        target: "${FDS_LOADER_SOURCE_PATH}"
    depends_on:
      - db
    tty: true
    stdin_open: true
    command: ["bash"]
  db:
    image: postgres:14-alpine
    # hostname: pacta-factset.example.com
    hostname: pacta-factset.postgres.database.azure.com
    environment:
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_DB: "${PGDATABASE}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
