---
services:
  data_loader:
    build:
      context: .
    volumes:
      - type: bind
        source: factset-loader
        target: /mnt/factset-loader
    depends_on:
      - db
    tty: true
    stdin_open: true
    command: ["bash"]
  db:
    image: postgres:15-alpine
    # hostname: pacta-factset.example.com
    hostname: pacta-factset.postgres.database.azure.com
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: fds
      POSTGRES_PASSWORD: SuperSecret1234
